spring:
  profiles:
    active:
      - dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
	  
---
server:
  port: 8202
spring:
  profiles: uat
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
